export const ADD_TODO = "ADD_TODO"
export const NEW_TODO = "NEW_TODO"
export const REMOVE_TODO = "REMOVE_TODO"
export const MARK_COMPLETE = "MARK_COMPLETE"
export const ADD_FAVORITE = "ADD_FAVORITE"
export const REMOVE_FAVORITE = "REMOVE_FAVORITE"